#![forbid(unsafe_code)]
//! Single authoritative Block II instruction encoding and decoding table.

use agc_word::AgcWord;
use serde::{Deserialize, Serialize};
use std::fmt;
use thiserror::Error;

/// Block II basic and extended mnemonics.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Mnemonic {
    /// Add memory to A.
    Ad,
    /// Add A to erasable memory and store there.
    Ads,
    /// Increase magnitude away from zero.
    Aug,
    /// Branch on zero to fixed address.
    Bzf,
    /// Branch on zero or negative to fixed address.
    Bzmf,
    /// Clear and add.
    Ca,
    /// Count, compare, and skip.
    Ccs,
    /// Clear and subtract.
    Cs,
    /// Double add to storage.
    Das,
    /// Double clear and add.
    Dca,
    /// Double clear and subtract.
    Dcs,
    /// Diminish magnitude toward zero.
    Dim,
    /// Divide.
    Dv,
    /// Double exchange.
    Dxch,
    /// Interrupt generated by software.
    EdrupT,
    /// Make the next instruction extended.
    Extend,
    /// Increment erasable memory.
    Incr,
    /// Add memory to the next instruction.
    Index,
    /// Disable interrupts.
    Inhint,
    /// Exchange L and erasable memory.
    Lxch,
    /// Logical AND.
    Mask,
    /// Multiply.
    Mp,
    /// Modular subtract.
    Msu,
    /// Exchange Q and erasable memory.
    Qxch,
    /// Read channel and mask with A.
    Rand,
    /// Read channel into A.
    Read,
    /// Enable interrupts.
    Relint,
    /// Return from interrupt and restore instruction context.
    Resume,
    /// Read channel and OR with A.
    Ror,
    /// Read channel and XOR with A.
    Rxor,
    /// Subtract memory from A.
    Su,
    /// Transfer control and save return in Q.
    Tc,
    /// Transfer control to fixed memory.
    Tcf,
    /// Transfer A to erasable storage, with overflow skip.
    Ts,
    /// Write A AND channel back to channel.
    Wand,
    /// Write A OR channel back to channel.
    Wor,
    /// Write A to channel.
    Write,
    /// Exchange A and erasable memory.
    Xch,
}

impl Mnemonic {
    /// Canonical assembler spelling.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ad => "AD",
            Self::Ads => "ADS",
            Self::Aug => "AUG",
            Self::Bzf => "BZF",
            Self::Bzmf => "BZMF",
            Self::Ca => "CA",
            Self::Ccs => "CCS",
            Self::Cs => "CS",
            Self::Das => "DAS",
            Self::Dca => "DCA",
            Self::Dcs => "DCS",
            Self::Dim => "DIM",
            Self::Dv => "DV",
            Self::Dxch => "DXCH",
            Self::EdrupT => "EDRUPT",
            Self::Extend => "EXTEND",
            Self::Incr => "INCR",
            Self::Index => "INDEX",
            Self::Inhint => "INHINT",
            Self::Lxch => "LXCH",
            Self::Mask => "MASK",
            Self::Mp => "MP",
            Self::Msu => "MSU",
            Self::Qxch => "QXCH",
            Self::Rand => "RAND",
            Self::Read => "READ",
            Self::Relint => "RELINT",
            Self::Resume => "RESUME",
            Self::Ror => "ROR",
            Self::Rxor => "RXOR",
            Self::Su => "SU",
            Self::Tc => "TC",
            Self::Tcf => "TCF",
            Self::Ts => "TS",
            Self::Wand => "WAND",
            Self::Wor => "WOR",
            Self::Write => "WRITE",
            Self::Xch => "XCH",
        }
    }

    /// Parses canonical and common pseudo-operation spellings.
    pub fn parse(input: &str) -> Option<Self> {
        match input
            .trim()
            .trim_end_matches('*')
            .to_ascii_uppercase()
            .as_str()
        {
            "AD" => Some(Self::Ad),
            "ADS" => Some(Self::Ads),
            "AUG" => Some(Self::Aug),
            "BZF" => Some(Self::Bzf),
            "BZMF" => Some(Self::Bzmf),
            "CA" | "CAF" => Some(Self::Ca),
            "CCS" => Some(Self::Ccs),
            "CS" | "COM" => Some(Self::Cs),
            "DAS" => Some(Self::Das),
            "DCA" => Some(Self::Dca),
            "DCS" | "DCOM" => Some(Self::Dcs),
            "DIM" => Some(Self::Dim),
            "DV" => Some(Self::Dv),
            "DXCH" => Some(Self::Dxch),
            "EDRUPT" => Some(Self::EdrupT),
            "EXTEND" => Some(Self::Extend),
            "INCR" => Some(Self::Incr),
            "INDEX" | "NDX" => Some(Self::Index),
            "INHINT" => Some(Self::Inhint),
            "LXCH" => Some(Self::Lxch),
            "MASK" => Some(Self::Mask),
            "MP" | "SQUARE" => Some(Self::Mp),
            "MSU" => Some(Self::Msu),
            "QXCH" => Some(Self::Qxch),
            "RAND" => Some(Self::Rand),
            "READ" => Some(Self::Read),
            "RELINT" => Some(Self::Relint),
            "RESUME" => Some(Self::Resume),
            "ROR" => Some(Self::Ror),
            "RXOR" => Some(Self::Rxor),
            "SU" => Some(Self::Su),
            "TC" | "TCR" | "RETURN" => Some(Self::Tc),
            "TCF" => Some(Self::Tcf),
            "TS" | "OVSK" => Some(Self::Ts),
            "WAND" => Some(Self::Wand),
            "WOR" => Some(Self::Wor),
            "WRITE" => Some(Self::Write),
            "XCH" => Some(Self::Xch),
            _ => None,
        }
    }

    /// Whether this operation requires a preceding `EXTEND` in memory.
    pub const fn is_extended(self) -> bool {
        matches!(
            self,
            Self::Aug
                | Self::Bzf
                | Self::Bzmf
                | Self::Dca
                | Self::Dcs
                | Self::Dim
                | Self::Dv
                | Self::EdrupT
                | Self::Mp
                | Self::Msu
                | Self::Qxch
                | Self::Rand
                | Self::Read
                | Self::Ror
                | Self::Rxor
                | Self::Su
                | Self::Wand
                | Self::Wor
                | Self::Write
        )
    }
}

impl fmt::Display for Mnemonic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Decoded instruction and execution metadata.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct DecodedInstruction {
    /// Operation.
    pub mnemonic: Mnemonic,
    /// Address, channel, or literal K field.
    pub operand: u16,
    /// Complete 15-bit instruction word.
    pub raw: AgcWord,
    /// Whether decoding used extended context.
    pub extended: bool,
    /// Nominal machine-cycle count.
    pub cycles: u8,
}

/// Instruction encoding failure.
#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum EncodeError {
    /// Operand is wider than the instruction's K field.
    #[error("operand {operand:#o} exceeds {bits}-bit field for {mnemonic}")]
    OperandOutOfRange {
        /// Operation.
        mnemonic: Mnemonic,
        /// Supplied operand.
        operand: u16,
        /// Field width.
        bits: u8,
    },
}

/// Decodes every possible word under explicit basic/extended context.
pub const fn decode(raw: AgcWord, extended: bool) -> DecodedInstruction {
    let bits = raw.raw();
    let opcode = (bits >> 12) & 0o7;
    let quarter = (bits >> 10) & 0o3;
    let (mnemonic, operand, cycles) = if extended {
        match opcode {
            0 => match (bits >> 9) & 0o7 {
                0 => (Mnemonic::Read, bits & 0o777, 2),
                1 => (Mnemonic::Write, bits & 0o777, 2),
                2 => (Mnemonic::Rand, bits & 0o777, 2),
                3 => (Mnemonic::Wand, bits & 0o777, 2),
                4 => (Mnemonic::Ror, bits & 0o777, 2),
                5 => (Mnemonic::Wor, bits & 0o777, 2),
                6 => (Mnemonic::Rxor, bits & 0o777, 2),
                _ => (Mnemonic::EdrupT, bits & 0o777, 1),
            },
            1 if quarter == 0 => (Mnemonic::Dv, bits & 0o1777, 6),
            1 => (Mnemonic::Bzf, bits & 0o7777, 1),
            2 => match quarter {
                0 => (Mnemonic::Msu, bits & 0o1777, 2),
                1 => (Mnemonic::Qxch, bits & 0o1777, 2),
                2 => (Mnemonic::Aug, bits & 0o1777, 2),
                _ => (Mnemonic::Dim, bits & 0o1777, 2),
            },
            3 => (Mnemonic::Dca, bits & 0o7777, 3),
            4 => (Mnemonic::Dcs, bits & 0o7777, 3),
            5 => (Mnemonic::Index, bits & 0o7777, 2),
            6 if quarter == 0 => (Mnemonic::Su, bits & 0o1777, 2),
            6 => (Mnemonic::Bzmf, bits & 0o7777, 1),
            _ => (Mnemonic::Mp, bits & 0o7777, 3),
        }
    } else {
        match opcode {
            0 => match bits & 0o7777 {
                0o3 => (Mnemonic::Relint, 0, 1),
                0o4 => (Mnemonic::Inhint, 0, 1),
                0o6 => (Mnemonic::Extend, 0, 1),
                operand => (Mnemonic::Tc, operand, 1),
            },
            1 if quarter == 0 => (Mnemonic::Ccs, bits & 0o1777, 2),
            1 => (Mnemonic::Tcf, bits & 0o7777, 1),
            2 => match quarter {
                0 => (Mnemonic::Das, bits & 0o1777, 3),
                1 => (Mnemonic::Lxch, bits & 0o1777, 2),
                2 => (Mnemonic::Incr, bits & 0o1777, 2),
                _ => (Mnemonic::Ads, bits & 0o1777, 2),
            },
            3 => (Mnemonic::Ca, bits & 0o7777, 2),
            4 => (Mnemonic::Cs, bits & 0o7777, 2),
            5 if quarter == 0 && bits & 0o7777 == 0o17 => (Mnemonic::Resume, 0, 2),
            5 => match quarter {
                0 => (Mnemonic::Index, bits & 0o1777, 2),
                1 => (Mnemonic::Dxch, bits & 0o1777, 3),
                2 => (Mnemonic::Ts, bits & 0o1777, 2),
                _ => (Mnemonic::Xch, bits & 0o1777, 2),
            },
            6 => (Mnemonic::Ad, bits & 0o7777, 2),
            _ => (Mnemonic::Mask, bits & 0o7777, 2),
        }
    };
    DecodedInstruction {
        mnemonic,
        operand,
        raw,
        extended,
        cycles,
    }
}

/// Encodes a canonical instruction. Pseudo-operations are lowered by callers.
pub fn encode(mnemonic: Mnemonic, operand: u16) -> Result<AgcWord, EncodeError> {
    encode_with_context(mnemonic, operand, false)
}

/// Encodes an instruction with explicit extended context. This distinction is
/// required for `INDEX`, whose extended form has a wider K field.
pub fn encode_with_context(
    mnemonic: Mnemonic,
    operand: u16,
    extended_context: bool,
) -> Result<AgcWord, EncodeError> {
    let (base, mask, bits) = match mnemonic {
        Mnemonic::Relint => (0o00003, 0, 0),
        Mnemonic::Inhint => (0o00004, 0, 0),
        Mnemonic::Extend => (0o00006, 0, 0),
        Mnemonic::Resume => (0o50017, 0, 0),
        Mnemonic::Tc => (0o00000, 0o7777, 12),
        Mnemonic::Ccs => (0o10000, 0o1777, 10),
        Mnemonic::Tcf => (0o10000, 0o7777, 12),
        Mnemonic::Das => (0o20000, 0o1777, 10),
        Mnemonic::Lxch => (0o22000, 0o1777, 10),
        Mnemonic::Incr => (0o24000, 0o1777, 10),
        Mnemonic::Ads => (0o26000, 0o1777, 10),
        Mnemonic::Ca => (0o30000, 0o7777, 12),
        Mnemonic::Cs => (0o40000, 0o7777, 12),
        Mnemonic::Index if !extended_context => (0o50000, 0o1777, 10),
        Mnemonic::Dxch => (0o52000, 0o1777, 10),
        Mnemonic::Ts => (0o54000, 0o1777, 10),
        Mnemonic::Xch => (0o56000, 0o1777, 10),
        Mnemonic::Ad => (0o60000, 0o7777, 12),
        Mnemonic::Mask => (0o70000, 0o7777, 12),
        Mnemonic::Read => (0o00000, 0o777, 9),
        Mnemonic::Write => (0o01000, 0o777, 9),
        Mnemonic::Rand => (0o02000, 0o777, 9),
        Mnemonic::Wand => (0o03000, 0o777, 9),
        Mnemonic::Ror => (0o04000, 0o777, 9),
        Mnemonic::Wor => (0o05000, 0o777, 9),
        Mnemonic::Rxor => (0o06000, 0o777, 9),
        Mnemonic::EdrupT => (0o07000, 0o777, 9),
        Mnemonic::Dv => (0o10000, 0o1777, 10),
        Mnemonic::Bzf => (0o10000, 0o7777, 12),
        Mnemonic::Msu => (0o20000, 0o1777, 10),
        Mnemonic::Qxch => (0o22000, 0o1777, 10),
        Mnemonic::Aug => (0o24000, 0o1777, 10),
        Mnemonic::Dim => (0o26000, 0o1777, 10),
        Mnemonic::Dca => (0o30000, 0o7777, 12),
        Mnemonic::Dcs => (0o40000, 0o7777, 12),
        Mnemonic::Index => (0o50000, 0o7777, 12),
        Mnemonic::Su => (0o60000, 0o1777, 10),
        Mnemonic::Bzmf => (0o60000, 0o7777, 12),
        Mnemonic::Mp => (0o70000, 0o7777, 12),
    };
    if operand & !mask != 0 {
        return Err(EncodeError::OperandOutOfRange {
            mnemonic,
            operand,
            bits,
        });
    }
    AgcWord::try_from_raw(base | (operand & mask)).map_err(|_| EncodeError::OperandOutOfRange {
        mnemonic,
        operand,
        bits,
    })
}

/// Formats a decoded instruction in canonical octal assembly syntax.
pub fn disassemble(instruction: DecodedInstruction) -> String {
    match instruction.mnemonic {
        Mnemonic::Extend | Mnemonic::Relint | Mnemonic::Inhint | Mnemonic::Resume => {
            instruction.mnemonic.to_string()
        }
        _ => format!("{} {:04o}", instruction.mnemonic, instruction.operand),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_words_decode_in_both_contexts() {
        for raw in 0..=0o77777 {
            let word = AgcWord::try_from_raw(raw).unwrap();
            assert_eq!(decode(word, false).raw, word);
            assert_eq!(decode(word, true).raw, word);
        }
    }

    #[test]
    fn representative_encodings_round_trip() {
        for (mnemonic, operand) in [
            (Mnemonic::Tc, 0o2345),
            (Mnemonic::Ads, 0o777),
            (Mnemonic::Ts, 0o1234),
            (Mnemonic::Rxor, 0o321),
            (Mnemonic::Mp, 0o4567),
        ] {
            let word = encode(mnemonic, operand).unwrap();
            let decoded = decode(word, mnemonic.is_extended());
            assert_eq!(decoded.mnemonic, mnemonic);
            assert_eq!(decoded.operand, operand);
        }
    }
}
